### ISSUE TITLE
Rspec descriptions overdone

### ISSUE THREAD

**Issue by atz** [sul-dlss/moab-versioning#6]
Rspec lines like:

``` ruby
describe '=========================== INSTANCE METHODS ===========================' do
```

This leads to error reportage like:

```
Failures:

  1) Moab::FileGroup =========================== INSTANCE METHODS =========================== Moab::FileGroup#add_physical_file
     Failure/Error: group.add_physical_file(pathname)
     NoMethodError:
       undefined method `path' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007fd90e54dac8>
     # ./lib/moab/file_instance.rb:59:in `eql?'
     # ./lib/moab/file_instance.rb:65:in `=='
     # ./lib/moab/file_group.rb:238:in `add_physical_file'
     # ./spec/unit_tests/moab/file_group_spec.rb:397:in `block (3 levels) in <top (required)>'

Finished in 4.44 seconds (files took 0.78777 seconds to load)
307 examples, 1 failure

Failed examples:

rspec ./spec/unit_tests/moab/file_group_spec.rb:375 # Moab::FileGroup =========================== INSTANCE METHODS =========================== Moab::FileGroup#add_physical_file
```

This is annoying, unnecessary and damages readability.  Such descriptions should be revised, converted to comments or if nothing else, just removed entirely.

**Comment by atz** [comment]
Fuller execution looks like:
```
rspec -fd $_

Moab::FileGroup
  Moab::FileGroup#initialize
  =========================== INSTANCE ATTRIBUTES ===========================
    Moab::FileGroup#group_id
    Moab::FileGroup#data_source
    Moab::FileGroup#file_count
    Moab::FileGroup#byte_count
    Moab::FileGroup#block_count
    Moab::FileGroup#files
    Moab::FileGroup#signature_hash
    Moab::FileGroup#base_directory
  =========================== INSTANCE METHODS ===========================
    Moab::FileGroup#path_hash
    Moab::FileGroup#path_list
    Moab::FileGroup#path_hash_subset
    Moab::FileGroup#add_file
    Moab::FileGroup#add_file_instance
    Moab::FileGroup#remove_file_having_path
    Moab::FileGroup#is_descendent_of_base?
    Moab::FileGroup#group_from_directory_digests
    Moab::FileGroup#group_from_directory
    Moab::FileGroup#harvest_directory
    Moab::FileGroup#add_physical_file (FAILED - 1)

Failures:

  1) Moab::FileGroup =========================== INSTANCE METHODS =========================== Moab::FileGroup#add_physical_file
     Failure/Error: group.add_physical_file(pathname)
     NoMethodError:
       undefined method `path' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007f8285d1d850>
     # ./lib/moab/file_instance.rb:59:in `eql?'
     # ./lib/moab/file_instance.rb:65:in `=='
     # ./lib/moab/file_group.rb:238:in `add_physical_file'
     # ./spec/unit_tests/moab/file_group_spec.rb:392:in `block (3 levels) in <top (required)>'

Finished in 0.14319 seconds (files took 0.63299 seconds to load)
20 examples, 1 failure

Failed examples:

rspec ./spec/unit_tests/moab/file_group_spec.rb:370 # Moab::FileGroup =========================== INSTANCE METHODS =========================== Moab::FileGroup#add_physical_file

```
After some cleanup:
```
rspec -fd $_

Moab::FileGroup
  #initialize
  INSTANCE ATTRIBUTES
    #group_id
    #data_source
    #file_count
    #byte_count
    #block_count
    #files
    #signature_hash
    #base_directory
  INSTANCE METHODS
    #path_hash
    #path_list
    #path_hash_subset
    #add_file
    #add_file_instance
    #remove_file_having_path
    #is_descendent_of_base?
    #group_from_directory_digests
    #group_from_directory
    #harvest_directory
    #add_physical_file (FAILED - 1)

Failures:

  1) Moab::FileGroup INSTANCE METHODS #add_physical_file
     Failure/Error: group.add_physical_file(pathname)
     NoMethodError:
       undefined method `path' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007fdc835c5848>
     # ./lib/moab/file_instance.rb:59:in `eql?'
     # ./lib/moab/file_instance.rb:65:in `=='
     # ./lib/moab/file_group.rb:238:in `add_physical_file'
     # ./spec/unit_tests/moab/file_group_spec.rb:392:in `block (3 levels) in <top (required)>'

Finished in 0.14991 seconds (files took 0.62547 seconds to load)
20 examples, 1 failure

Failed examples:

rspec ./spec/unit_tests/moab/file_group_spec.rb:370 # Moab::FileGroup INSTANCE METHODS #add_physical_file

```

But this latter error summary shows why even the clean `INSTANCE METHODS` header is not particularly helpful.

**Comment by darrenleeweber** [comment]
Agreed, proposed solution looks alright to me.

**Comment by atz** [comment]
Seemingly resolved now.
